<?php

namespace Database\Seeders;

use App\Models\Appointment;
use App\Models\Availability;
use App\Models\Client;
use Illuminate\Database\Seeder;

class AppointmentSeeder extends Seeder
{
    // Populates dummy appointments (pending, confirmed, canceled). 
    // Past statuses (e.g., completed/expired) will be processed later by the scheduled task.
    public function run(): void
    {
        // Fetch all generated clients and availabilities
        $clients = Client::all();
        $availabilities = Availability::all();

        // Safety check to ensure we have clients to link to appointments
        if ($clients->isEmpty()) {
            $this->command->info('No clients found. Creating 20 dummy clients automatically...');
            $clients = Client::factory(20)->create();
        }

        foreach ($availabilities as $availability) {

            // 40% chance of the slot having some appointment activity
            if (rand(1, 100) <= 40) {

                // 15% chance of being a rebooked slot (one canceled, followed by a new active one)
                $isRebooked = rand(1, 100) <= 15;

                if ($isRebooked) {
                    // 1. Create the old canceled appointment
                    Appointment::create([
                        'client_id' => $clients->random()->id,
                        'availability_id' => $availability->id,
                        'status' => 'canceled',
                        'notes' => 'Client canceled in advance.',
                        'created_at' => now()->subDays(3),
                        'updated_at' => now()->subDays(2),
                    ]);

                    // 2. Create the new active appointment that took the slot
                    $activeStatus = rand(1, 100) <= 50 ? 'confirmed' : 'pending';

                    Appointment::create([
                        'client_id' => $clients->random()->id,
                        'availability_id' => $availability->id,
                        'status' => $activeStatus,
                        'notes' => 'Squeezed-in appointment for the canceled slot.',
                        'created_at' => now()->subDays(1),
                        'updated_at' => now()->subDays(1),
                    ]);

                    // Ensure the slot is blocked
                    $availability->update(['is_available' => false]);
                } else {
                    // Normal flow: only 1 appointment for the slot

                    // Picks a random status based ONLY on your requested rules
                    $statuses = ['pending', 'confirmed', 'canceled'];
                    $status = $statuses[array_rand($statuses)];

                    // Create the appointment
                    Appointment::create([
                        'client_id' => $clients->random()->id,
                        'availability_id' => $availability->id,
                        'status' => $status,
                        'notes' => 'Appointment automatically generated by the system.',
                    ]);

                    // If the appointment is active (pending or confirmed), block the slot
                    if ($status !== 'canceled') {
                        $availability->update(['is_available' => false]);
                    }
                }
            }
        }
    }
}
